language: python

os:
  - linux

python:
  - 2.7
  - 3.6

sudo: false

install:
  - python -m pip install -r requirements.txt
  - python -m pip install numpy scipy

script:
  - python -c "import scooby; print(scooby.investigate())"
  - python -c "import scooby; print(scooby.investigate(core='numpy'))"
  - python -c "import scooby; print(scooby.investigate(additional=['mock', 'foo']))"
  - python -c "import scooby; print(scooby.investigate(additional=['foo',]))"
  - python -c "import scooby, mock; print(scooby.investigate(additional=[mock,]))"
  - python -c "import scooby, mock; print(scooby.investigate(additional=mock))"
  - python -c "import scooby, mock; print(scooby.investigate(additional=mock)._repr_html_())"

notifications:
  email:
    recipients:
      - info@pyvista.org
    on_success: never
    on_failure: never

deploy:
  - provider: pypi
    user: banesullivan
    distributions: sdist
    on:
      repo: banesullivan/scooby
      branch: master
      tags: true
      python: 3.6
    password: $PYPI_PASSWORD
